name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: brew install supabase/tap/supabase

      - name: Set Remote DB
        shell: bash
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: supabase db remote set $SUPABASE_URL

      - name: Push Migrations
        run: supabase db push

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install

      - run: npx tailwindcss -i ./styles/main.css -o ./static/styles/main.css -m

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: your-deno-deploy-project # the name of the project on Deno Deploy
          entrypoint: main.ts # the entrypoint to deploy
          import-map: import_map.json
